name: Build and scan container image

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REPOSITORY: shanduur
  IMAGE_NAME: template-ci-container
  IMAGE_TAG: ${{ github.sha }}

jobs:
  image_lint:
    name: Lint Containerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile

  image_security_scan:
    strategy:
      matrix:
        arch: [amd64, arm64]
    name: Build and scan container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build an image from Containerfile
        run: ./scripts/build.sh
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-${{ matrix.arch }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
